name: ShopAds
main: org.hpiz.ShopAds.ShopAds
version: 1.5
author: Hpiz
commands:
  ads:
    description: Control creation and receiving of ad
    usage:
    aliases: ad
  shops:
    description: Actions for current shops
    usage:
    aliases: